export const stateOptions = [
  { key: "AL", value: "Alabama", text: "Alabama" },
  { key: "AK", value: "Alaska", text: "Alaska" },
  { key: "AZ", value: "Arizona", text: "Arizona" },
  { key: "AR", value: "Arkansas", text: "Arkansas" },
  { key: "CA", value: "California", text: "California" },
  { key: "CO", value: "Colorado", text: "Colorado" },
  { key: "CT", value: "Connecticut", text: "Connecticut" },
  { key: "DE", value: "Delaware", text: "Delaware" },
  { key: "FL", value: "Florida", text: "Florida" },
  { key: "GA", value: "Georgia", text: "Georgia" },
  { key: "HI", value: "Hawaii", text: "Hawaii" },
  { key: "ID", value: "Idaho", text: "Idaho" },
  { key: "IL", value: "Illinois", text: "Illinois" },
  { key: "IN", value: "Indiana", text: "Indiana" },
  { key: "IA", value: "Iowa", text: "Iowa" },
  { key: "KS", value: "Kansas", text: "Kansas" },
  { key: "KY", value: "Kentucky", text: "Kentucky" },
  { key: "LA", value: "Louisiana", text: "Louisiana" },
  { key: "ME", value: "Maine", text: "Maine" },
  { key: "MD", value: "Maryland", text: "Maryland" },
  { key: "MA", value: "Massachusetts", text: "Massachusetts" },
  { key: "MI", value: "Michigan", text: "Michigan" },
  { key: "MN", value: "Minnesota", text: "Minnesota" },
  { key: "MS", value: "Mississippi", text: "Mississippi" },
  { key: "MO", value: "Missouri", text: "Missouri" },
  { key: "MT", value: "Montana", text: "Montana" },
  { key: "NE", value: "Nebraska", text: "Nebraska" },
  { key: "NV", value: "Nevada", text: "Nevada" },
  { key: "NH", value: "New Hampshire", text: "New Hampshire" },
  { key: "NJ", value: "New Jersey", text: "New Jersey" },
  { key: "NM", value: "New Mexico", text: "New Mexico" },
  { key: "NY", value: "New York", text: "New York" },
  { key: "NC", value: "North Carolina", text: "North Carolina" },
  { key: "ND", value: "North Dakota", text: "North Dakota" },
  { key: "OH", value: "Ohio", text: "Ohio" },
  { key: "OK", value: "Oklahoma", text: "Oklahoma" },
  { key: "OR", value: "Oregon", text: "Oregon" },
  { key: "PA", value: "Pennsylvania", text: "Pennsylvania" },
  { key: "RI", value: "Rhode Island", text: "Rhode Island" },
  { key: "SC", value: "South Carolina", text: "South Carolina" },
  { key: "SD", value: "South Dakota", text: "South Dakota" },
  { key: "TN", value: "Tennessee", text: "Tennessee" },
  { key: "TX", value: "Texas", text: "Texas" },
  { key: "UT", value: "Utah", text: "Utah" },
  { key: "VT", value: "Vermont", text: "Vermont" },
  { key: "VA", value: "Virginia", text: "Virginia" },
  { key: "WA", value: "Washington", text: "Washington" },
  { key: "WV", value: "West Virginia", text: "West Virginia" },
  { key: "WI", value: "Wisconsin", text: "Wisconsin" },
  { key: "WY", value: "Wyoming", text: "Wyoming" }
];
